### ISSUE TITLE
[Future Requests] More flexible adjustment

### ISSUE THREAD

**Issue by github-1348A55** [Drahsid/ResizableHUD#5]
When I register a hud, it is fixed at the current value and prevents me from trying to change it in-game.
Is it possible to make a rough change manually first and then change the values to adjust them?
I can get around this by operating the desired hud first and then registering it, but this method alone is a bit inconvenient.

Scale presets.
60/80/90/100/110/120/140/160/180/200 (Standard Scale)
I think it would be more convenient if could select from here and finetune them individually.

Ability to restore defaults in case of misconfiguration.
It would be nice to be able to easily revert the pos or scale or transparency of the hud in question to the in-game defaults in case of visual anomalies.
This clears up confusion quickly and makes reconfiguration easier.

**Comment by Drahsid** [comment]
I think if I just add a button to refresh the values from the game, you will be able to select `No Position` and `No Scale` to do this. I will add this shortly.

**Comment by Drahsid** [comment]
I added the option I discussed above. From 1.1.7 onward, if you want to update the position/scale/opacity of an entry, disable said option and click "Refresh Values". For example, to update position, you can toggle on "No Position", and click "Refresh Values".
