### ISSUE TITLE
Addon Inspector not working

### ISSUE THREAD

**Issue by Nysterian** [Drahsid/ResizableHUD#6]
I have used this plugin in the past to resize some windows, and I've had them saved for a while, so I haven't touched the plugin since then...

Now I wanted to add a new setting to it, but the "Draw Addon Inspector" button doesn't seem to do anything anymore, whether "Draw Only Visible" is selected or not.

I do wonder if it's some incompatibility with some other plugin, but I have absolutely no clue what other plugin it could be.

**Comment by Drahsid** [comment]
Looks like something broke with a recent dalamud update, I am investigating.

**Comment by Drahsid** [comment]
I just fixed this issue. Once it gets merged in the Dalamud repo, just update it in-game. Thanks for bringing this to my attention!

**Comment by Nysterian** [comment]
> I just fixed this issue. Once it gets merged in the Dalamud repo, just update it in-game. Thanks for bringing this to my attention!

You're very welcome, thanks for fixing it so fast!!
